api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
        yaml:     ['application/x-yaml']
        csv:      ['text/csv']
        html:     ['text/html']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    version: 1.0.0
    show_webby: false
    title: 'Streetnames API'
    description: 'Streetnames API from Posti.fi postal service.'
